### ISSUE TITLE
I/O Error when trying to run example after fresh install 

### ISSUE THREAD

**Issue by floftus-at-csm** [pimoroni/inkydev-python#4]
Hi There,
I'm trying to use the inkydev screen but am running into the same error when running any of the examples.
I am using a Raspberry Pi 4 with the standard 32 bit Debian Bullseye OS
I initially installed inkydev with the standard install script but then uninstalled and installed using the install-bullseye.sh file. The error persists after installing either
`Traceback (most recent call last):
  File "/home/pi/Pimoroni/inkydev/examples/colour_sequence.py", line 8, in <module>
    inkydev = InkyDev()
  File "/usr/local/lib/python3.9/dist-packages/inkydev/__init__.py", line 33, in __init__
    self._i2c.write_byte_data(I2C_ADDRESS, REG_CONFIG, 0x0F)
  File "/usr/local/lib/python3.9/dist-packages/smbus2/smbus2.py", line 455, in write_byte_data
    ioctl(self.fd, I2C_SMBUS, msg)
OSError: [Errno 121] Remote I/O error`

I2C and SPI are enabled on the Pi and when I check if there is an I2C connection using `sudo i2cdetect -y 1`
one does come up as '3a'

I have tried to install with the pip package and the newest version from github

any advice would be appreciated

**Comment by Gadgetoid** [comment]
I think this is my fault for not releasing a new version of the library since the address fix. Will sort ASAP.

**Comment by Gadgetoid** [comment]
Okay, library updated. Fingers crossed. Try:

```
python3 -m pip install inkydev --upgrade
```

**Comment by floftus-at-csm** [comment]
perfect, it works now - thanks!

**Comment by Gadgetoid** [comment]
Whew, excellent!
