### ISSUE TITLE
600x448 7-Color display: Is there a way to change the amount of time it takes to update the image?

### ISSUE THREAD

**Issue by 22mac** [pimoroni/inkydev-python#5]
I've seen others able to change duration and voltage used to reset the display when refreshing the screen for pimoroni products, but not for the 7-color display. I know that in the inky_uc8159 class definition the _update method is used to call a data refresh with the command self._send_command(UC8159_DRF).

UC8159_DRF = 0x12 is set as part of the class definition. I think the 0x12 command performs the repeated clearing (+/- voltage polarizing) for each color AND produces the new image to the screen. 

It's during the "self._send_command(UC8159_DRF)" method call that the screen does it's flashing of different colors and different time intervals that I'd like to shorten. Has anyone been able to figure out a way to make this work? I've reached the end of my ability here, but don't want to give up on using this awesome board for my project.

**Comment by ageeandakeyboard** [comment]
Hi,
Unfortunately update time is set by the screen manufactures which takes into account small differences in each display and the ambient temperature.

Sorry about that 
Regards
Gee
